/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apps;

import javax.swing.JOptionPane;

/**
 *
 * @author Andika Risky Septiawan
 */
public class HomeFtw extends javax.swing.JFrame {
    int bahasa = 0, 
            jmlHuruf = 0, 
            waktu = 0;

    /**
     * Creates new form ftw
     */
    public HomeFtw() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RadioButton = new javax.swing.ButtonGroup();
        Checkbox = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cbBhsIndo = new javax.swing.JCheckBox();
        cbBhsInggris = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        cb4kata = new javax.swing.JCheckBox();
        cb5kata = new javax.swing.JCheckBox();
        cb6kata = new javax.swing.JCheckBox();
        cb7kata = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        rb1dtk = new javax.swing.JRadioButton();
        rb2dtk = new javax.swing.JRadioButton();
        rb3dtk = new javax.swing.JRadioButton();
        btnMulai = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home FTW");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Apps/icon.png")).getImage());
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bahasa Kata", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Futura Bk BT", 1, 16))); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        cbBhsIndo.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        cbBhsIndo.setText("Bahasa Indonesia");
        cbBhsIndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBhsIndoActionPerformed(evt);
            }
        });
        jPanel1.add(cbBhsIndo);

        cbBhsInggris.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        cbBhsInggris.setText("Bahasa Inggris");
        jPanel1.add(cbBhsInggris);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Maksimal jumlah huruf per kata", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Futura Bk BT", 1, 16))); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        Checkbox.add(cb4kata);
        cb4kata.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        cb4kata.setText("4");
        jPanel2.add(cb4kata);

        Checkbox.add(cb5kata);
        cb5kata.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        cb5kata.setText("5");
        jPanel2.add(cb5kata);

        Checkbox.add(cb6kata);
        cb6kata.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        cb6kata.setText("6");
        jPanel2.add(cb6kata);

        Checkbox.add(cb7kata);
        cb7kata.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        cb7kata.setText("7");
        jPanel2.add(cb7kata);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Timer per kata", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Futura Bk BT", 1, 16))); // NOI18N
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        RadioButton.add(rb1dtk);
        rb1dtk.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        rb1dtk.setText("1 detik");
        jPanel3.add(rb1dtk);

        RadioButton.add(rb2dtk);
        rb2dtk.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        rb2dtk.setText("2 detik");
        jPanel3.add(rb2dtk);

        RadioButton.add(rb3dtk);
        rb3dtk.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        rb3dtk.setText("3 detik");
        jPanel3.add(rb3dtk);

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_START);

        btnMulai.setText("Mulai");
        btnMulai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMulaiMouseClicked(evt);
            }
        });
        getContentPane().add(btnMulai, java.awt.BorderLayout.LINE_END);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Futura Md BT", 1, 24)); // NOI18N
        jLabel1.setText("Fast Typing Word");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.add(jLabel1, java.awt.BorderLayout.CENTER);

        jLabel2.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        jLabel2.setText("Andika Risky Septiawan | XII RPL B");
        jPanel4.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbBhsIndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBhsIndoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBhsIndoActionPerformed

    private void btnMulaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMulaiMouseClicked
        // TODO add your handling code here:
        pilihanUser();
    }//GEN-LAST:event_btnMulaiMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFtw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFtw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFtw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFtw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFtw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Checkbox;
    private javax.swing.ButtonGroup RadioButton;
    private javax.swing.JButton btnMulai;
    private javax.swing.JCheckBox cb4kata;
    private javax.swing.JCheckBox cb5kata;
    private javax.swing.JCheckBox cb6kata;
    private javax.swing.JCheckBox cb7kata;
    private javax.swing.JCheckBox cbBhsIndo;
    private javax.swing.JCheckBox cbBhsInggris;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton rb1dtk;
    private javax.swing.JRadioButton rb2dtk;
    private javax.swing.JRadioButton rb3dtk;
    // End of variables declaration//GEN-END:variables

    private void pilihanUser() {
        // Pilihan bahasa dari user
        if (cbBhsIndo.isSelected() && cbBhsInggris.isSelected()) {
            bahasa = 3;
        } else if (cbBhsInggris.isSelected()){
            bahasa = 2;
        } else if (cbBhsIndo.isSelected()) {
            bahasa = 1;
        } else if (!(cbBhsIndo.isSelected() && cbBhsInggris.isSelected())) {
            JOptionPane.showMessageDialog(null, "Pilih bahasa terlebih dahulu");
        }
        
        // Pilihan waktu dari user
        if (rb1dtk.isSelected()) {
            waktu = 1;
        } else if (rb2dtk.isSelected()) {
            waktu = 2;
        } else if (rb3dtk.isSelected()) {
            waktu = 3;
        } else if (!(rb1dtk.isSelected() && rb2dtk.isSelected() && rb3dtk.isSelected())) {
            JOptionPane.showMessageDialog(null, "Pilih timer terlebih dahulu");
        }
        
        // Pilihan jumlah kata dari user
        if (cb4kata.isSelected()) {
            jmlHuruf = 4;
        } else if (cb5kata.isSelected()) {
            jmlHuruf = 5;
        } else if (cb6kata.isSelected()) {
            jmlHuruf = 6;
        } else if (cb7kata.isSelected()) {
            jmlHuruf = 7;
        } else if (!(cb4kata.isSelected() && cb5kata.isSelected() && cb6kata.isSelected() && cb7kata.isSelected())) {
            JOptionPane.showMessageDialog(null, "Pilih jumlah kata terlebih dahulu");
        }
        
        if (!(bahasa == 0) && !(waktu == 0) && !(jmlHuruf ==0)) {
            MainFtw mf = new MainFtw();
            mf.fromHome(bahasa, waktu, jmlHuruf);
            mf.setVisible(true);
            this.setVisible(false);
        }
    }
}
