/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apps;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Andika Risky Septiawan
 */
public class MainFtw extends javax.swing.JFrame {
    
    // parameter yang dikirim dari form HomeFtw
    int userBahasaJml, userTimer, userJmlHuruf;
    
    void fromHome(int bahasa, int waktu, int jmlHuruf) {
        userBahasaJml = bahasa;
        userTimer = waktu;
        userJmlHuruf = jmlHuruf;
        kata();
    }
    
    // untuk membuat  akurasi typing
    Timer timer, timerGanti;
    int Waktu = 60;
    int maxProg = 10;
    int progress = 3;
    
    // mendeklarasikan kata untuk mengambil data dari class Kata
    String[] indo4kata,indo5kata, indo6kata, indo7kata;
    String[] eng4kata, eng5kata, eng6kata, eng7kata;
    
    int jmlKata = 0;
    int pilihBahasa = 0;
    
    // untuk mengganti kata jika user tidak validasi kata
    int gantiKata = userTimer;

    /**
     * Creates new form MainFtw
     */
    
    public MainFtw() {
        initComponents();
        
        // men-setting progressbar atau akurasi typing
        progresbarKata.setMinimum(0);
        progresbarKata.setMaximum(maxProg);
        progresbarKata.setValue(progress);
        progresbarKata.setStringPainted(true);
        /* memanggil method mGantiKata() agar setiap waktu yang ditentukan
            berganti otomatis sesuai waktu yang ditentukan */
        mGantiKata();
        // membuat timer mundur
        countDown();
        // menuliskan jumlah kata yang berhasil diketik
        labelJmlkata.setText(String.valueOf(jmlKata));
        // agar cursor saat di run otomatis ke textbox
        tbKata.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progresbarKata = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        labelKata = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tbKata = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        labelJmlkata = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        labelTimer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FTW Play");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Apps/icon.png")).getImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        progresbarKata.setForeground(new java.awt.Color(0, 102, 102));
        progresbarKata.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(progresbarKata, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 51, 621, 24));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kata / Word", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Futura Bk BT", 1, 14))); // NOI18N

        labelKata.setFont(new java.awt.Font("Futura Bk BT", 1, 18)); // NOI18N
        labelKata.setText("kata-word");
        labelKata.setAlignmentY(0.0F);
        labelKata.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addComponent(labelKata)
                .addGap(252, 252, 252))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelKata)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 86, 621, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Typing", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Futura Bk BT", 1, 14))); // NOI18N

        tbKata.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tbKata.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        tbKata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbKataKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(tbKata, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(tbKata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 621, -1));

        jLabel3.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        jLabel3.setText("Jumlah kata :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));

        labelJmlkata.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        labelJmlkata.setText("30");
        getContentPane().add(labelJmlkata, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, -1, -1));

        btnKeluar.setFont(new java.awt.Font("Futura Bk BT", 1, 16)); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKeluarMouseClicked(evt);
            }
        });
        getContentPane().add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Futura Md BT", 1, 24)); // NOI18N
        jLabel5.setText(" Fast Typing Word ");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        labelTimer.setFont(new java.awt.Font("Futura Bk BT", 1, 18)); // NOI18N
        labelTimer.setToolTipText("");
        getContentPane().add(labelTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbKataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbKataKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (tbKata.getText().trim().equals(labelKata.getText().trim())) {
                tbKata.setText("");
                kata();
                if (progress + 2 < maxProg) {
                    progress = progress + 2;
                    gantiKata = userTimer;
                }
                jmlKata = jmlKata + 1;
                labelJmlkata.setText(String.valueOf(jmlKata));
            } else {
                tbKata.setText("");
            }
        }
    }//GEN-LAST:event_tbKataKeyPressed

    private void btnKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeluarMouseClicked
        // TODO add your handling code here:
        timer.stop();
        timerGanti.stop();
        JOptionPane.showMessageDialog(null, "Game Berakhir\n"
                        + "Jumlah kata yang benar : " + jmlKata );
        HomeFtw hf = new HomeFtw();
        hf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnKeluarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFtw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFtw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFtw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFtw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFtw().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelJmlkata;
    private javax.swing.JLabel labelKata;
    private javax.swing.JLabel labelTimer;
    private javax.swing.JProgressBar progresbarKata;
    private javax.swing.JFormattedTextField tbKata;
    // End of variables declaration//GEN-END:variables

    private void kata() {
        Random rand = new Random();
        Random plhBhs = new Random();
        int rn4indo, rn5indo, rn6indo, rn7indo;
        int rn4ingg, rn5ingg, rn6ingg, rn7ingg;
        
        // membuat object class Kata
        Kata kt = new Kata();
        // memasukkan data dari class ke variabel yang telah dibuat
        indo4kata = kt.indo4kata;
        indo5kata = kt.indo5kata;
        indo6kata = kt.indo6kata;
        indo7kata = kt.indo7kata;
        eng4kata = kt.eng4kata;
        eng5kata = kt.eng5kata;
        eng6kata = kt.eng6kata;
        eng7kata = kt.eng7kata;
        
        rn4indo = rand.nextInt(indo4kata.length);
        rn5indo = rand.nextInt(indo5kata.length);
        rn6indo = rand.nextInt(indo6kata.length);
        rn7indo = rand.nextInt(indo7kata.length);
        rn4ingg = rand.nextInt(eng4kata.length);
        rn5ingg = rand.nextInt(eng5kata.length);
        rn6ingg = rand.nextInt(eng6kata.length);
        rn7ingg = rand.nextInt(eng7kata.length);
        
        pilihBahasa = plhBhs.nextInt(2);
        
        if (userBahasaJml == 1) {
            if (userJmlHuruf == 4) {
                labelKata.setText(indo4kata[rn4indo]);
            } else if (userJmlHuruf == 5) {
                labelKata.setText(indo5kata[rn5indo]);
            } if (userJmlHuruf == 6) {
                labelKata.setText(indo6kata[rn6indo]);
            } if (userJmlHuruf == 7) {
                labelKata.setText(indo7kata[rn7indo]);
            }
        } if (userBahasaJml == 2) {
            if (userJmlHuruf == 4) {
                labelKata.setText(eng4kata[rn4ingg]);
            } else if (userJmlHuruf == 5) {
                labelKata.setText(eng5kata[rn5ingg]);
            } if (userJmlHuruf == 6) {
                labelKata.setText(eng6kata[rn6ingg]);
            } if (userJmlHuruf == 7) {
                labelKata.setText(eng7kata[rn7ingg]);
            }
        } else if (userBahasaJml == 3) {
            if (userJmlHuruf == 4) {
                if (pilihBahasa == 0) {
                    labelKata.setText(indo4kata[rn4indo]);
                } else if (pilihBahasa == 1) {
                    labelKata.setText(eng4kata[rn4ingg]);
                }
            } else if (userJmlHuruf == 5) {
                if (pilihBahasa == 0) {
                    labelKata.setText(indo5kata[rn5indo]);
                } else if (pilihBahasa == 1) {
                    labelKata.setText(eng5kata[rn5ingg]);
                }
            } else if (userJmlHuruf == 6) {
                if (pilihBahasa == 0) {
                    labelKata.setText(indo6kata[rn6indo]);
                } else if (pilihBahasa == 1) {
                    labelKata.setText(eng6kata[rn6ingg]);
                }
            } else if (userJmlHuruf == 7) {
                if (pilihBahasa == 0) {
                    labelKata.setText(indo7kata[rn7indo]);
                } else if (pilihBahasa == 1) {
                    labelKata.setText(eng7kata[rn7ingg]);
                }
            }
        } 
    }
   
    private void countDown() {
        timer = new Timer(1000, (ActionEvent e) -> {
            progress--;
            Waktu--;
            
            if (Waktu == 0) {
                timer.stop();
                timerGanti.stop();
                JOptionPane.showMessageDialog(null, "Game Berakhir\n"
                        + "Jumlah kata permenit : " + jmlKata + "\n"
                                + "Akurasi mengetik : " + progress);
                HomeFtw hf = new HomeFtw();
                hf.setVisible(true);
                this.setVisible(false);
            } else {
                progresbarKata.setValue(progress);
                labelTimer.setText(String.valueOf(Waktu));
            }
            
            if (progress < 0) {
                progress = 0;
            }
        });
        timer.start();
    }

    private void mGantiKata() {
        timerGanti = new Timer(1000, (ActionEvent e) -> {
            gantiKata--;
            
            if (gantiKata == 0) {
                kata();
                tbKata.setText("");
                gantiKata = userTimer;
            }
        });
        timerGanti.start();
    }
}
